### ISSUE TITLE
t/05_utils.t started to fail (with newest PPI?)

### ISSUE THREAD

**Issue by eserte** [Perl-Critic/Perl-Critic#858] opened 2019-04-25 22:38 UTC
The following test failure looks new:
```
#   Failed test 'parse_arg_list: foo( { bar() }, {}, 'blah' )'
#   at t/05_utils.t line 433.
#     Structures begin differing at:
#          $got->[0] = ARRAY(0x55b84e6440f8)
#     $expected->[0] = ' { bar() }'
# Looks like you failed 1 test of 156.
t/05_utils.t .................................. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/156 subtests 
```

There are no pass reports with the recent PPI releases (@wchristian: FYI):
```
****************************************************************
Regression 'mod:PPI'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      1.0000	      0.0684	  14.62
[1='eq_1.230'] 	     -0.0000	      0.0838	  -0.00
[2='eq_1.232'] 	     -0.0000	      0.0818	  -0.00
[3='eq_1.234'] 	     -0.1500	      0.0734	  -2.04
[4='eq_1.236'] 	     -0.0070	      0.0688	  -0.10
[5='eq_1.248'] 	     -1.0000	      0.1082	  -9.24
[6='eq_1.250'] 	     -1.0000	      0.0802	 -12.46

R^2= 0.683, N= 330, K= 7
****************************************************************
```

**Comment by preaction** [comment] 2019-04-26 10:47
I think this was caused by this change to PPI: https://github.com/adamkennedy/PPI/commit/7fd14b0a4334a1073ec93d6f5f7d0ed97eb3015f

So, PPI now parses this correctly as a hashref constructor, which means the test needs to change. If I apply the patch below, the test passes, but I have a lot of other failing tests on my machine for some reason...

```patch
diff --git a/t/05_utils.t b/t/05_utils.t
index 4c642473..3df53794 100644
--- a/t/05_utils.t
+++ b/t/05_utils.t
@@ -418,7 +418,7 @@ sub test_parse_arg_list {
         [
                 q/foo( { bar() }, {}, 'blah' )/
             =>  [
-                    ' { bar() }',
+                    [ '{ bar() }' ],
                     [ qw< {} > ],
                     [ q<'blah'> ],
                 ],
```

**Comment by wchristian** [comment] 2019-04-26 12:20
I've done a lot of releases yesterday, you might want to work your way forwards from https://metacpan.org/release/MITHALDU/PPI-1.238

**Comment by preaction** [comment] 2019-04-26 13:36
A `git bisect` confirms: https://github.com/adamkennedy/PPI/commit/7fd14b0a4334a1073ec93d6f5f7d0ed97eb3015f is the thing that changed to break this. I feel PPI is correctly parsing this, so this has to be fixed in Perl-Critic.

**Comment by shlomif** [comment] 2019-04-30 09:35
Hi! Please fix this issue as it causes build failures such as https://travis-ci.org/shlomif/Dir-Manifest/jobs/526162733 .

**Comment by petdance** [comment] 2019-05-14 22:06
Fixed: 6e6ce950311697ecb2b1302b68821be236106e64

**Closed by petdance** 2019-05-14 22:06 UTC

**Comment by jkeenan** [comment] 2019-05-23 01:55
Do you have an ETA for a CPAN release addressing this problem?

Today I went to install many 100s of CPAN modules against perl-5.30.0.  The FAIL for Perl::Critic was the most prominent failure.

Thank you very much.
Jim Keenan

**Comment by petdance** [comment] 2019-05-23 02:02
I've got an open issue at #871 for the release.
