### ISSUE TITLE
PPI mis-parse (?) results in erroneous  "Must end with a recognizable true value."

### ISSUE THREAD

**Issue by DannyThomas** [Perl-Critic/Perl-Critic#696] opened 2016-07-01 03:01 UTC
I only started using `perlcritic` over my code-base a few days ago
and was surprised to see it report this error for about 20 modules.
The reported line number for each file was well before the end.

I took one of the files and reduced it to this:

```
package  UQ::Net::AddressSpace;
use  warnings;
use  strict;
sub  v4_block {  my ($self, $id) = @_;  return $self->_sub_hash(['id', $id, 'v4-block']);  }
1;
```

which results in

```
Module does not end with "1;" at line 4, column 1.
```

problem goes away by
- changing 'v4_block' -> '_v4_block'
- removing '['
- appending ';' to end of line

So I went through each of the modules with v4/v6 functions/methods and
added a ';' after their '}'.

PPI does this

```
PPI::Statement
  PPI::Token::Word      'sub'
  PPI::Token::Whitespace    '   '
  PPI::Token::Number::Version   'v4'
  PPI::Token::Word      '_block'
  PPI::Token::Whitespace    '   '
  PPI::Structure::Block     { ... }
```

I haven't reported this to PPI as I'm not where any fix belongs

**Comment by otrosien** [comment] 2017-01-19 10:24
This very much looks like a PPI bug. The token after "sub" needs to be a word-token, but Number::Version takes precedence.

**Comment by moregan** [comment] 2017-01-19 18:42
A fix for this has been committed to PPI, and is waiting to be released: https://github.com/adamkennedy/PPI/issues/65  As I recall, PPI still needs to have some regressions addressed before its next release.

**Comment by moregan** [comment] 2017-05-22 18:20
adamkennedy/PPI#65 was fixed and released in PPI 1.222, so this ticket should be retested to see whether it, too, is now okay.

**Comment by petdance** [comment] 2017-05-23 02:19
@DannyThomas Can you please try this with the new PPI (and potentially with new Perl::Critic 1.127_01) and tell us if it's fixed for you?

**Comment by petdance** [comment] 2017-05-23 02:35
I added a test at f620916.  I'm closing this ticket unless I hear back from @DannyThomas that there is still a problem.

**Closed by petdance** 2017-05-23 02:35 UTC
Labels: Bug
