### ISSUE TITLE
Possible Bug in Perl::Critic::Policy::Subroutines::RequireFinalReturn

### ISSUE THREAD

**Issue by thaljef** [Perl-Critic/Perl-Critic#509] opened 2013-11-01 19:42 UTC
RT Ticket: http://rt.cpan.org/Ticket/Display.html?id=85938
Requested On: Thu Jun 06 13:20:30 2013
Requested By: buys444@gmail.com

---

Hi!

I found a bug in Perl::Critic::Policy::Subroutines::RequireFinalReturn in
revision 4126.

When I try to validate the following code "sub foo { if @a { return } }" I
get an error (that is perl ciritic crashes instead of telling me I'm doing
something stupid).

I'm not a perl expert and I'm using a version of perl critic called from a
complicated wrapper someone wrote years ago, so the problem could be there
as well.

I thought I would point it out in case it was a bug so that it could be
looked into.

Thanks

**Comment by petdance** [comment] 2017-01-07 22:44
Closed as not a bug.

**Closed** 2017-01-07 22:43 UTC
