### ISSUE TITLE
perlcritic.com domain expired

### ISSUE THREAD

**Issue by mjgardner** [Perl-Critic/Perl-Critic#1031] opened 2023-05-12 17:42 UTC
We need to get in touch with `perlcritic.com`’s owner to renew the domain name before it is snapped up by someone else, as it expired on May 3, 2023. http://perlcritic.com is currently returning an easyDNS error page noting the expiration. (The secure HTTPS https://perlcritic.com address refuses a connection entirely.)

The documentation lists the website as a place to try the software and the distribution metadata includes it as the homepage link, which is displayed on MetaCPAN. Further, the documentation also lists [`<team@perlcritic.com>`](mailto:team@perlcritic.com) as a contact for submitting new Policy modules.

**Comment by petdance** [comment] 2023-05-14 02:09
If someone wants to do this and keep perlcritic.com going, please do so. I am not going to myself.

**Comment by guest20** [comment] 2023-05-14 13:13
If one were to host this site, where would they find the content? Could it be pointed at a github pages, for example?

**Comment by petdance** [comment] 2023-05-14 17:16
I have no idea. I'd start by asking Jeff Thalhammer @thaljef

**Comment by oalders** [comment] 2023-06-30 14:25
So, it looks like this did get renewed. I think we could move the registration over to TPRF so that it doesn't expire moving forward. @thaljef is that something you'd like to do?

**Comment by thaljef** [comment] 2023-07-11 17:08
Yes, I renewed the domain. I apologize for the disruption. I would be happy to hand over the domain and the hosting of the service to a more permanent and responsible party. @oalders, who should I contact to get that started?

**Comment by oalders** [comment] 2023-07-11 17:50
Thanks for renewing @thaljef! I've sent a transfer request for the domain from the TPRF account. I just need a transfer auth code from you. You could email that to olaf@wundersolutions.com if that works for you. We could look at hosting after that. 😄

**Comment by thaljef** [comment] 2023-07-26 21:00
I use EasyDNS and I have requested the auth code. I will send it along when I receive it.

**Comment by oalders** [comment] 2023-07-26 21:11
Thanks @thaljef! I have initiated the transfer.

**Comment by petdance** [comment] 2023-10-17 02:42
Can this be closed now?

**Comment by oalders** [comment] 2023-10-17 14:18
I've just sent another domain name registration transfer request as it looks like the initial one failed.

**Comment by jonasbn** [comment] 2024-07-13 14:31
The transfer seems to have taken place, I believe this issue can be closed.

**Comment by oalders** [comment] 2024-07-13 16:09
Confirmed. We can close this. Thanks, @jonasbn!

**Closed** 2024-07-14 02:16 UTC

**Comment by thaljef** [comment] 2024-08-05 17:24
FYI, `whois` still shows my old DNS registrar (EasyDNS) as the DNS server names:

```
Domain Name: PERLCRITIC.COM
Registry Domain ID: 434021283_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.pairdomains.com
Registrar URL: http://www.pairdomains.com
Updated Date: 2023-10-23T04:30:12Z
Creation Date: 2006-05-03T06:14:20Z
Registry Expiry Date: 2026-05-03T06:14:20Z
Registrar: pair Networks, Inc. d/b/a pair Domains
Registrar IANA ID: 99
Registrar Abuse Contact Email:
Registrar Abuse Contact Phone:
Domain Status: ok https://icann.org/epp#ok
Name Server: DNS1.EASYDNS.COM                                 <------------------------ HERE
Name Server: DNS2.EASYDNS.NET                                   <------------------------ HERE
Name Server: DNS3.EASYDNS.CA                                     <------------------------ HERE
```

**Comment by oalders** [comment] 2024-10-02 22:02
@thaljef ^^^
